package api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SliderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSliderAllPropertiesEquals(Slider expected, Slider actual) {
        assertSliderAutoGeneratedPropertiesEquals(expected, actual);
        assertSliderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSliderAllUpdatablePropertiesEquals(Slider expected, Slider actual) {
        assertSliderUpdatableFieldsEquals(expected, actual);
        assertSliderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSliderAutoGeneratedPropertiesEquals(Slider expected, Slider actual) {
        assertThat(actual)
            .as("Verify Slider auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSliderUpdatableFieldsEquals(Slider expected, Slider actual) {
        assertThat(actual)
            .as("Verify Slider relevant properties")
            .satisfies(a -> assertThat(a.getPresentation()).as("check presentation").isEqualTo(expected.getPresentation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSliderUpdatableRelationshipsEquals(Slider expected, Slider actual) {
        // empty method
    }
}
